---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-json
        exclude: |
            (?x)^(
                boutiques/tests/example1/invocation_invalid.json
                | boutiques/tests/validator/invalid_json.json
            )$
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    # -   id: end-of-file-fixer
    # -   id: mixed-line-ending
    # -   id: trailing-whitespace

# Format YAML files
-   repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
    -   id: yamlfmt
        args: [--mapping, '4', --sequence, '4', --offset, '0']
        exclude: |
            (?x)^(
                boutiques/tests/import/config/.*
            )$

# Format TOML files
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.13.0
    hooks:
    -   id: pretty-format-toml
        args: [--autofix, --indent, '4']
        exclude: |
            (?x)^(
                boutiques/tests/import/config/.*
            )$

# Checks for spelling errors
-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    -   id: codespell
        args: [--toml, pyproject.toml]
        additional_dependencies: [tomli]
